[package]
name = "banglejs-emu"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.69"
base64 = "0.21.0"
crossbeam-channel = "0.5.7"
crossterm = "0.26.1"
env_logger = "0.10.0"
log = "0.4.17"
tui = "0.19.0"
wasmtime = "6.0.0"
