startup = "load();\n"
flash_initial_contents_file = "../Espruino/libs/banglejs/banglejs2_storage_default.c"

[storage."antonclk.info"]
contents = '{"type":"clock","name":"Anton Clock Plus","src":"antonclkplus.app.js"}'

[storage."antonclk.app.js"]
path = "../BangleApps/apps/antonclkplus/app.js"

[storage."antonclk.json"]
contents = '{"secondsMode": "Always", "secondsColoured": true, "secondsWithColon": true}'
