on:
  push:
    branches:
      - master

jobs:
  release:
    name: release ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-pc-windows-gnu
            os: win
          - target: x86_64-unknown-linux-musl
            os: linux
    steps:
      - uses: actions/checkout@master
      - name: Compile and release
        uses: rust-build/rust-build.action@v1.4.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OS: ${{ matrix.os }}
        with:
          RUSTTARGET: ${{ matrix.target }}
          UPLOAD_MODE: none
      - name: Upload
        uses: actions/upload-artifact@v3.1.2
        with:
          name: banglejs-emu-${{ matrix.os }}
          path: |
            output/banglejs-emu
            output/banglejs-emu.exe
