on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-11.0, ubuntu-20.04, windows-2019]
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - name: Build
        run: cargo build --release -vvv
      - name: Upload
        uses: actions/upload-artifact@v3.1.2
        with:
          name: banglejs-emu-${{ matrix.os }}
          path: |
            target/release/banglejs-emu
            target/release/banglejs-emu.exe
